### ISSUE TITLE
v1.1.0 Error: Could not find the input entity for

### ISSUE THREAD

**Issue by hirenreshamwala** [butthx/tgsnake#33]
Getting error when a new message received onNewMessage

```
Error: Could not find the input entity for {"CONSTRUCTOR_ID":2645671021,"SUBCLASS_OF_ID":47470215,"className":"PeerUser","classType":"constructor","userId":822063740}.
         Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
    at Object.<anonymous> (/var/www/Node/telegram-data/node_modules/telegram/client/users.js:294:15)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/Node/telegram-data/node_modules/telegram/client/users.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by butthx** [comment]
For first time you you should send a message  media (sticker). Next update maybe I'll fix that so it doesn't have to send message media (sticker) for the first time.

Thanks you for report it.

**Comment by butthx** [comment]
should have been fixed in the latest version. [Changelog](https://tgsnake.js.org/release)
